---
# Global Configuration Variables
ansible_python_interpreter: /usr/bin/python3

# Docker Configuration
docker_compose_version: "2.21.0"
docker_network_name: "{{ app_name }}_network"

# Application Defaults
app_user: "{{ ansible_user }}"
app_group: "{{ ansible_user }}"

# Security Configuration
session_secret: "portfolio-secret-change-in-production"
admin_username: "admin"
admin_password: "P@rtf0lioQFDVTR!"

# SSL Configuration
ssl_cert_path: "/etc/letsencrypt/live/{{ app_domain }}/fullchain.pem"
ssl_key_path: "/etc/letsencrypt/live/{{ app_domain }}/privkey.pem"

# Backup Configuration
backup_path: "{{ app_path }}/backups"
backup_schedule: "0 2 * * *"  # Daily at 2 AM

# Nginx Configuration
nginx_worker_processes: auto
nginx_worker_connections: 1024
nginx_client_max_body_size: "10M"

# Health Check Configuration
health_check_timeout: 30
health_check_max_retries: 10